# Generated by Django 4.2 on 2023-09-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todo_title_ar_todo_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
